src/zensvi/cv/segmentation/segmentation.py
src/zensvi/download/streetview_downloader.py
src/zensvi/download/utils/imtool.py
tests/test_zensvi.py

I added checkpoints for downloading and segmentation functions to enhance the stability.

added checkpoints

---

src/zensvi/cv/segmentation/segmentation.py
src/zensvi/download/streetview_downloader.py
tests/test_zensvi.py

fixed bug with checkpoints

---

src/zensvi/download/streetview_downloader.py
tests/test_zensvi.py

improved the _check_already function by using built-in set subtraction

improved the speed of checking pids

---

src/zensvi/cv/segmentation/segmentation.py

Modified variable names to avoid accidentally updating image file list

fixed variable name conflicts

---

src/zensvi/download/__init__.py
src/zensvi/download/streetview_downloader.py
tests/test_zensvi.py

added MLYDownloader to allow users to download images from Mapillary

created Mapillary Downloader

---

pyproject.toml
src/zensvi/cv/segmentation/segmentation.py
tests/test_zensvi.py

added panoptic segmentation task

added panoptic segmentation

---

src/zensvi/download/streetview_downloader.py

fixed bugs in dropping duplicates

include id_columns when dropping duplicates

---

pyproject.toml
src/zensvi/download/mapillary/utils/filter.py
src/zensvi/download/streetview_downloader.py
src/zensvi/download/utils/imtool.py
tests/test_zensvi.py

introduced subfolders when downloading with batch

batch sub-folders

---

pyproject.toml
src/zensvi/download/utils/geoprocess.py
tests/test_zensvi.py

prevent bugs when using points from different utm areas

new way of converting UTM to lat lon

---

src/zensvi/download/mapillary/controller/image.py
src/zensvi/download/streetview_downloader.py

introduced max_workers arg to control the number of concurrent requests. Added organization_id as kwargs

modified mly downloading code

---

src/zensvi/cv/segmentation/segmentation.py

MPS is now available in segmentation. make sure to:
- Use torch => 2.1.0 (pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu)
- Set environment variable: conda env config vars set PYTORCH_ENABLE_MPS_FALLBACK=1

MPS for segmentation

---

src/zensvi/download/base.py
src/zensvi/download/gsv.py
src/zensvi/download/mly.py
tests/test_gsv.py
tests/test_mly.py

implemented an option to download metadata only

allow metada-only download

---

src/zensvi/download/gsv.py
src/zensvi/download/utils/imtool.py
tests/test_gsv.py

improved GSVDownloader by filtering out black areas for old images

improved GSV downloader

---

src/zensvi/download/gsv.py
src/zensvi/download/mapillary/controller/image.py
src/zensvi/download/mapillary/interface.py
src/zensvi/download/mapillary/models/api/vector_tiles.py
src/zensvi/download/mly.py
src/zensvi/download/utils/imtool.py
src/zensvi/utils/log.py
tests/test_gsv.py
tests/test_mly.py

added log functions

---

pyproject.toml
src/zensvi/download/mapillary/models/api/vector_tiles.py
src/zensvi/download/mapillary/models/geojson.py
src/zensvi/download/mly.py

improved the efficiency of loading cache files

improved cache loading

---

pyproject.toml
src/zensvi/download/gsv.py
src/zensvi/download/mapillary/controller/image.py
src/zensvi/download/mapillary/models/api/vector_tiles.py
src/zensvi/download/mapillary/utils/filter.py
src/zensvi/download/mly.py
src/zensvi/download/utils/imtool.py
tests/test_mly.py

changed the processing logic for mapillary downloader

speed up geojson process

---

pyproject.toml
src/zensvi/download/gsv.py
tests/test_gsv.py
tests/test_mly.py

added download_depth argument in GSVDownloader

added depth

---

docs/autoapi/zensvi/download/mapillary/config/api/entities/index.rst
docs/autoapi/zensvi/download/mapillary/config/api/general/index.rst
docs/autoapi/zensvi/download/mapillary/config/api/vector_tiles/index.rst
docs/autoapi/zensvi/download/mapillary/models/api/entities/index.rst
docs/autoapi/zensvi/download/mapillary/models/api/general/index.rst
docs/autoapi/zensvi/download/mapillary/models/api/vector_tiles/index.rst
docs/example.ipynb
poetry.lock
pyproject.toml
src/zensvi/visualization/__init__.py
src/zensvi/visualization/kde.py
tests/test_places365.py
tests/test_segmentation.py
tests/test_visualization.py

created kde plot

---

poetry.lock
pyproject.toml
src/zensvi/transform/__init__.py
src/zensvi/transform/image_to_pointcloud.py
tests/test_point_cloud.py

code for generating point cloud

added point cloud

---

src/zensvi/transform/transform_image.py
tests/test_image_transformation.py

can now specify whether to use only upper half of the image

added a new argument for using only upper half

---

poetry.lock
pyproject.toml
src/zensvi/metadata/mly_metadata.py
tests/test_mly_metadata.py

geopolars was causing an issue, I removed it

removed geopolars dependency

---

src/zensvi/cv/segmentation/segmentation.py
tests/test_segmentation.py

- Modify pixel ratio calculation to count valid pixels and normalize correctly
- Add comprehensive test for transformed segmentation pixel ratio calculation
- Ensure pixel ratios sum to approximately 1 across different image transformations

Enhance pixel ratio calculation in segmentation with improved normalization

---

src/zensvi/cv/depth_estimation/torchhub/facebookresearch_dinov2_main/dinov2/eval/linear.py
src/zensvi/cv/depth_estimation/torchhub/facebookresearch_dinov2_main/dinov2/train/ssl_meta_arch.py
src/zensvi/cv/depth_estimation/torchhub/facebookresearch_dinov2_main/dinov2/train/train.py
src/zensvi/cv/object_detection/object_detection.py
tests/test_object_detection.py

- Add support for optional image and summary output directories
- Implement grouped object detection summary with count per image
- Update method signatures to allow more flexible processing
- Add comprehensive test cases for new functionality
- Support saving summaries in JSON and CSV formats with optional grouping

Enhance object detection with flexible output options and grouped summaries
